Allprojects bugfix
odesseyHQ/nibbles-logtrack pull request #16
Opened 2023-10-09 14:42 UTC by aghilodessey

-->Allprojects bugfix

2023-10-09 17:32 UTC, nihiannd requested changes

2023-10-09 17:32 UTC, nihiannd commented on client/src/pages/logs-screen/Logs.tsx
> +  console.log(selectedProject);
Remove console

2023-10-10 04:12 UTC, aghilodessey commented on client/src/pages/logs-screen/Logs.tsx
> +  console.log(selectedProject);
Done

2023-10-10 07:35 UTC, nihiannd approved these changes

2023-10-10 07:37 UTC, merged