Create Project and Projectlist api integration done
odesseyHQ/nibbles-logtrack pull request #8
Opened 2023-09-27 12:06 UTC by aghilodessey

-->Create Project and Projectlist api integration done
![wed1](https://github.com/odesseyHQ/nibbles-logtrack/assets/132039951/a7c05f8b-f844-49ac-8594-1f87ee9c802c)
![wed2](https://github.com/odesseyHQ/nibbles-logtrack/assets/132039951/526061fc-b11d-410c-bd93-de20b9f6a48c)

2023-09-28 06:25 UTC, nihiannd requested changes

2023-09-28 06:25 UTC, nihiannd commented on client/src/pages/projects/hooks/projects.hooks.ts
> +  const url = "http://logger.odesseylabs.com/api/project";
Move baseurl to the .env file and call where ever needed

2023-09-28 06:25 UTC, nihiannd commented on client/src/pages/projects/hooks/projects.hooks.ts
> +    Authorization: "Bearer NIBBLES_ODESSEY",
Move to .env file

2023-09-28 06:25 UTC, nihiannd commented on client/src/pages/projects/hooks/projects.hooks.ts
> +  const CREATE_PROJECT = `http://logger.odesseylabs.com/api/project/create`;
move baseurl to .env

2023-09-28 06:25 UTC, nihiannd commented on client/src/pages/projects/hooks/projects.hooks.ts
> +    Authorization: "Bearer NIBBLES_ODESSEY",
move to .env

2023-09-29 05:12 UTC, aghilodessey commented on client/src/pages/projects/hooks/projects.hooks.ts
> +  const url = "http://logger.odesseylabs.com/api/project";
Done

2023-09-29 05:12 UTC, aghilodessey commented on client/src/pages/projects/hooks/projects.hooks.ts
> +    Authorization: "Bearer NIBBLES_ODESSEY",
Done

2023-09-29 05:12 UTC, aghilodessey commented on client/src/pages/projects/hooks/projects.hooks.ts
> +  const CREATE_PROJECT = `http://logger.odesseylabs.com/api/project/create`;
Done

2023-09-29 05:12 UTC, aghilodessey commented on client/src/pages/projects/hooks/projects.hooks.ts
> +    Authorization: "Bearer NIBBLES_ODESSEY",
Done

2023-09-29 06:22 UTC, nihiannd approved these changes

2023-09-29 06:23 UTC, merged